version: 2

sources:
  - name: gz_raw_data

    tables:

      - name: raw_gz_product
        columns:
          - name: products_id
            description: XXX
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: XXX

      - name: raw_gz_sales
        description: sales of Greenweez / we have one row per product_id found in each orders_id
        columns:
          - name: date_date
            description: date of purchase

          - name: orders_id
            description: XXX

          - name: products_id
            description: XXX

          - name: revenue
            description: XXX

          - name: quantity
            description: XXX



      - name: raw_gz_ship
        columns:
          - name: orders_id
            description: XXX
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: XXX
          - name: log_cost
            description: XXX
          - name: ship_cost
            description: XXX
      - name: adwords
        identifier: raw_gz_adwords
        columns:
          - name: date_date
          - name: campaign_name
        tests:
        - unique:
            column_name: "(date_date || '-' ||campaign_key)"
        - not_null:
            column_name: "(date_date || '-' ||campaign_key)"
      - name: facebook
        identifier: raw_gz_facebook
        columns:
          - name: date_date
          - name: campaign_name
        tests:
        - unique:
            column_name: "(date_date || '-' ||campaign_key)"
        - not_null:
            column_name: "(date_date || '-' ||campaign_key)"
      - name: criteo
        identifier: raw_gz_criteo
        columns:
          - name: date_date
          - name: campaign_name
        tests:
        - unique:
            column_name: "(date_date || '-' ||campaign_key)"
        - not_null:
            column_name: "(date_date || '-' ||campaign_key)"
      - name: bing
        identifier: raw_gz_bing
        columns:
          - name: date_date
          - name: campaign_name
        tests:
        - unique:
            column_name: "(date_date || '-' ||campaign_key)"
        - not_null:
            column_name: "(date_date || '-' ||campaign_key)"